set(_CATKIN_CURRENT_PACKAGE "kmriiwa_tool_planning")
set(kmriiwa_tool_planning_VERSION "0.3.0")
set(kmriiwa_tool_planning_MAINTAINER "AP <poolearj@gmail.com>")
set(kmriiwa_tool_planning_PACKAGE_FORMAT "1")
set(kmriiwa_tool_planning_BUILD_DEPENDS )
set(kmriiwa_tool_planning_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "kmriiwa_optimisation")
set(kmriiwa_tool_planning_BUILDTOOL_DEPENDS "catkin")
set(kmriiwa_tool_planning_BUILDTOOL_EXPORT_DEPENDS )
set(kmriiwa_tool_planning_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "kmriiwa_optimisation")
set(kmriiwa_tool_planning_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "kmriiwa_optimisation")
set(kmriiwa_tool_planning_TEST_DEPENDS )
set(kmriiwa_tool_planning_DOC_DEPENDS )
set(kmriiwa_tool_planning_URL_WEBSITE "http://moveit.ros.org/")
set(kmriiwa_tool_planning_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(kmriiwa_tool_planning_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(kmriiwa_tool_planning_DEPRECATED "")