set(_CATKIN_CURRENT_PACKAGE "kmriiwa_optimisation")
set(kmriiwa_optimisation_VERSION "0.0.0")
set(kmriiwa_optimisation_MAINTAINER "alastair <alastair.poole@strath.ac.uk>, carlos <carlossuarezzapico@gmail.com>")
set(kmriiwa_optimisation_PACKAGE_FORMAT "2")
set(kmriiwa_optimisation_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "tf" "sensor_msgs" "std_msgs" "trajectory_msgs" "visualization_msgs" "message_generation" "message_runtime" "iiwa_msgs")
set(kmriiwa_optimisation_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(kmriiwa_optimisation_BUILDTOOL_DEPENDS "catkin")
set(kmriiwa_optimisation_BUILDTOOL_EXPORT_DEPENDS )
set(kmriiwa_optimisation_EXEC_DEPENDS "geometry_msgs" "tf" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs" "visualization_msgs" "message_runtime")
set(kmriiwa_optimisation_RUN_DEPENDS "geometry_msgs" "tf" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs" "visualization_msgs" "message_runtime")
set(kmriiwa_optimisation_TEST_DEPENDS )
set(kmriiwa_optimisation_DOC_DEPENDS )
set(kmriiwa_optimisation_URL_WEBSITE "")
set(kmriiwa_optimisation_URL_BUGTRACKER "")
set(kmriiwa_optimisation_URL_REPOSITORY "")
set(kmriiwa_optimisation_DEPRECATED "")